### PR TITLE
Uploaded a python program for simpson's 1/3 rule

### LINKED ISSUE #2: simpson's 1/3 rule
create a python program for simpson's 1/3 rule.

### PR DESCRIPTION
**Pull request by sujoy-coder**
Sir,
I have uploaded a python program for simpson's 1/3 rule in order to resolve an issue. I hope you approved and marged it. This contribution is for HacktoberFest. fixes #2 

Thank You ...

### CODE REVIEW

**Review by varchasa — COMMENTED** [review]
Hey sujoy, its ma'am here. Can you implement it using one user defined function only ?

**Comment by sujoy-coder** [comment]
Sure sir...  I will do that by today..... 
Sir can I try to implement it with object oriented manner.

**Comment by varchasa** [comment]
Yes you can.

**Comment by sujoy-coder** [comment]
OK sir...

**Comment by sujoy-coder** [comment]
Ma'am, I have made necessary changes in the code. please check it.
fixes #4 


Thank You...

**Review by varchasa — APPROVED** [review]

**Review by varchasa — APPROVED** [review]

**Comment by sujoy-coder** [comment]
Ma'am, can i work on different issue

**Comment by varchasa** [comment]
Yes u can work.

**Pull request merged**
